order_type_changer="tradeTypeSpinner"
fast_order_type="//*[@text='سریع']"
trigger_order_type="//*[@text='حد ضرر']"
sell_section="bck_tab_sell"
price="priceMET"
ammount="amountMET"
trigger_ammount="triggerMET"
prices="price"
buy="//*[@text='خرید بیت‌کوین']"
sell="//*[@text='فروش بیت‌کوین']"
increase_found="//*[@text='افزایش موجودی']"
c_100_perceent="//*[@text='100%']"
increase_amount="addAmountIV"
confirm="confirm"
order_successfull="//*[@text='با موفقیت اضافه شد']"